### ISSUE TITLE
Interface graphique GitHub !

### ISSUE THREAD

**Issue by Nutr4x** [CPLN/en-voiture#19]
Pour les personnes ayant des difficultés à visualiser mentalement ou par Git l'arborescence des branches je vous propose cette solution qui m'aide incroyablement 
https://www.gitkraken.com/ (Avancé)
ou 
https://desktop.github.com/ (Basique)

GitHub est pris en charge Bon week-end.

@Nutr4x

![capture](https://cloud.githubusercontent.com/assets/14217740/14925052/baf13b14-0e45-11e6-9785-80a340e8b4d9.PNG)
![capture2](https://cloud.githubusercontent.com/assets/14217740/14925087/e311c442-0e45-11e6-863e-6ae93c455555.PNG)

**Comment by SteeveDroz** [comment]
@Nutr4x Merci pour le partage, je clos cette discussion car il ne s'agit pas de la déclaration d'un problème et je mets votre commentaire fort à propos dans le [Wiki](../wiki/Aide-à-la-visualisation).
